[22기 이동명] Add: Kakao Signup/Signin feature
wecode-bootcamp-korea/22-2nd-22percent-backend pull request #13
Opened 2021-07-22 13:59 UTC by dom-lee

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 카카오 소셜 로그인 엔드포인트
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-07-22 14:00 UTC, dom-lee commented
![image](https://user-images.githubusercontent.com/46280353/126651751-10d760f2-4940-496f-ab6a-05113d575d34.png)

2021-07-23 01:26 UTC, kst6294 requested changes
코드상에 문제는 없어보입니다. 피드백 반영해주세요!
그런데 테스트코드가 동작하고 있는건가요?

2021-07-23 01:26 UTC, kst6294 commented on users/tests.py
> +        access_token = jwt.encode({"user_id": user.id}, SECRET_KEY, ALGORITHM)
일반 로그인 테스트 기능구현때 놓친 부분인데, 이미 view 로직에서 access_token을 반환하고 있기 때문에, 여기서 굳이 다시 실행하지 않아도 괜찮습니다. 실제 값으로 비교해주세요.
```
ex) response = c.post('/users/signin', json.dumps(user), content_type="application/json")
      access_token = response.json()['access_token']
```

2021-07-23 02:44 UTC, dom-lee commented on users/tests.py
> +        access_token = jwt.encode({"user_id": user.id}, SECRET_KEY, ALGORITHM)
![image](https://user-images.githubusercontent.com/46280353/126731834-55d1a317-a1aa-472c-836d-be105171501e.png)

2021-07-23 02:44 UTC, dom-lee commented on users/tests.py
> +        access_token = jwt.encode({"user_id": user.id}, SECRET_KEY, ALGORITHM)
수정하였습니다.

2021-07-23 04:23 UTC, kst6294 approved these changes
LGTM 👍

2021-07-23 04:23 UTC, merged