[22기 이준영] Deal list 구현
wecode-bootcamp-korea/22-2nd-22percent-backend pull request #15
Opened 2021-07-23 05:34 UTC by Pratiable

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Deal list 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- mortgage list 구현
- mortgage closed list 구현
- mortgage closed pagination 구현
- individual list 구현

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

<img width="995" alt="스크린샷 2021-07-23 오후 2 20 29" src="https://user-images.githubusercontent.com/77120067/126740997-6fc57034-2d6c-4f0e-bb05-fed9c2bf644b.png">
<img width="1009" alt="스크린샷 2021-07-23 오후 2 21 05" src="https://user-images.githubusercontent.com/77120067/126741012-87106c94-1358-40b1-b89d-ff07987688c9.png">
<img width="1006" alt="스크린샷 2021-07-23 오후 2 21 21" src="https://user-images.githubusercontent.com/77120067/126741018-7eedcf54-64f1-43da-af73-08a3539e3970.png">

![스크린샷 2021-07-23 오후 2 20 22](https://user-images.githubusercontent.com/77120067/126741081-43efdfc9-9420-4e16-a2a7-8ba082571eae.png)

2021-07-26 02:25 UTC, kst6294 requested changes
확인바랍니다!

2021-07-26 02:25 UTC, kst6294 commented on deals/tests.py
> +    def setUp(self):
setUp 의 경우 각각의 test 가 동작할 때마다 실행됩니다. 즉 테스트마다 그 내용이 변경될 수 있는 객체를 생성할 수 있습니다.
전체에서 공통적으로 사용하고, 그 값이 변경되지 않는 객체들을 생성하는 경우라면 setUpTestData() 메소드를 사용해보시는 것도 좋겠습니다. 해당 메소드는 setUp 처럼 매번 실행하지 않고, 한 번만 생성후에 사용하게 됩니다.

2021-07-27 01:07 UTC, Pratiable commented on deals/tests.py
> +    def setUp(self):
넵 수정했습니다! Prefetch를 이용한 쿼리 최적화도 진행해보았습니다

2021-07-27 06:57 UTC, kst6294 commented
conflict 해결해주세요!

2021-07-27 07:03 UTC, Pratiable commented
해결했습니다!

2021-07-27 07:06 UTC, merged